module.exports = [
  {
    id: 1,
    user_id: 1,
    group_id: 1,
    name: "Keu!",
    longitude: -0.0815,
    latitude: 51.5266,
    type: "Restaurant",
  },
  {
    id: 2,
    user_id: 1,
    group_id: 1,
    name: "Island Poke",
    longitude: -0.0807,
    latitude: 51.5248,
    type: "Restaurant",
  },
  {
    id: 3,
    user_id: 1,
    group_id: 2,
    name: "Hanwoo Village",
    longitude: -0.1041,
    latitude: 51.5367,
    type: "Restaurant",
  },
  {
    id: 4,
    user_id: 1,
    group_id: 2,
    name: "Lina Stores",
    longitude: -0.125,
    latitude: 51.5372,
    type: "Restaurant",
  },
  {
    id: 5,
    user_id: 1,
    group_id: 2,
    name: "Relais de Venise",
    longitude: -0.151,
    latitude: 51.5182,
    type: "Restaurant",
  },
  {
    id: 6,
    user_id: 2,
    group_id: 2,
    name: "Din Tai Fung",
    longitude: -0.1527,
    latitude: 51.5146,
    type: "Restaurant",
  },
  {
    id: 7,
    user_id: 2,
    group_id: 2,
    name: "Jinjuu",
    longitude: -0.1392,
    latitude: 51.5127,
    type: "Restaurant",
  },
  {
    id: 8,
    user_id: 6,
    group_id: 1,
    name: "Subway",
    longitude: -0.081,
    latitude: 51.5249,
    type: "Restaurant",
  },
];
